# Install main packages
- name: OCServ | Generic | Install main packages
  ansible.builtin.package:
    name: "{{ ocserv_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - OCServ | Restart service
  when: ocserv_packages
  register: ocserv_packages_changed

# Install extra packages
- name: OCServ | Generic | Install extra packages
  ansible.builtin.package:
    name: "{{ ocserv_extra_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocserv_extra_packages
